name: Build

on:
  pull_request:

jobs:
  do_build:
    runs-on: ubuntu-latest
    steps:
      - name: Do the build
        run: echo Beep boop doing a build

  always_skipped:
    runs-on: ubunut-latest
    if: false
    steps:
      - name: This never runs
        run: echo Sad beep noises

